version: "3.7"

services:
  app:
    image: artur/robot:latest
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: world

    expose:
      # Opens port 3306 on the container
      - '3306'

    depends_on:
            - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: world
    ports:
      - '3307:3306'
    
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: world
    volumes:
      - world:/var/lib/mysql
volumes:
  world:
